### ISSUE TITLE
Change client identification

### ISSUE THREAD

**Issue by acegilz** [dryruby/rack-throttle#18]
Instead of IP address, I would like to use the user_id to establish the limits.
From the documentation I got this:  

"If you wish to instead use a more granular, application-specific identifier such as a session key or a user account name, you need only subclass a throttling strategy implementation and override the #client_identifier method."

However I don't understand how to do it..

Thanks

**Comment by FreekingDean** [comment]
@acegilz are you asking how to subclass the throttle strategy & use that, or how to write the `get_user_id_from_session` method?

**Comment by scalp42** [comment]
@FreekingDean I think he meant how to subclass it.

**Comment by FreekingDean** [comment]
I don't think the original asker is still actively searching, but here it goes.

If you are using the second module you can do something like this:
```ruby
# config/initializers/client_based_id_second_limiter.rb
module Rack
  module Throttle
    class ClientBasedIdSecond < Second
      protected
      def client_identifier(request)
        # Get your client ID from the request
        # or from other source here.
      end
    end
  end
end
```

```ruby
# config/application.rb
require 'rack/throttle'

class Application < Rails::Application
  config.middleware.use Rack::Throttle::ClientBasedIdSecond, max: 10
end
```

Here is a random google find on how to subclass in ruby incase anyone is wondering. http://rubylearning.com/satishtalim/ruby_inheritance.html

**Comment by acegilz** [comment]
@FreekingDean that would be cool, haven't found a way yet (however honestly stopped looking at it) Couldn't make it with your code

**Comment by scalp42** [comment]
What was the issue @acegilz ?
