### ISSUE TITLE
use different rate-limiting for controllers

### ISSUE THREAD

**Issue by gabrieltong** [dryruby/rack-throttle#23]
my web application has two parts, one for web, one for api. 

I want to different interval rate-limiting for the them

api  : `use Rack::Throttle::Hourly,   :max => 100   # requests`
web : `use Rack::Throttle::Interval, :min => 1.0   # seconds`

**Comment by OscarBarrett** [comment]
You can create some custom middleware to do so.
For example (untested, though I've used something similar):

```ruby
# app/middleware/throttlers.rb
module ThrottleHelper
  def path_starts_with?(path)
    path_info = (Rails.application.routes.recognize_path request.url rescue {}) || {}
    !path_info[:controller].nil? && path_info[:controller].start_with?(path)
  end
end

class ApiHourlyThrottler < Rack::Throttle::Hourly
  include ThrottleHelper

  def allowed?(request)
    if path_starts_with?('/api')
      super
    else
      true
    end
  end
end

class WebIntervalThrottler < Rack::Throttle::Interval
  include ThrottleHelper

  def allowed?(request)
    if !path_starts_with?('/api')
      super
    else
      true
    end
  end
end
```

Then in `application.rb`
```ruby
config.middleware.use 'ApiHourlyThrottler',   max: 100, ...
config.middleware.use 'WebIntervalThrottler', min: 1.0, ...
```

Plenty you can do to make this suit your needs: matching on controllers, throttling only certain routes etc.

**Comment by FreekingDean** [comment]
@OscarBarrett has the correct approach. It seems you are looking to add middleware based on the path, which I do not believe is possible.
