### ISSUE TITLE
No tag for 0.4.0

### ISSUE THREAD

**Issue by ssandeep** [dryruby/rack-throttle#26]
The 0.4.0 version of the gem available at https://rubygems.org/gems/rack-throttle doesn't have per second limit constraint. But in the github repo, it is available. Can you please add a tag for the current version in the github repo so that I can use the github source directly in my project's gemfile?

**Comment by brandonhilkert** [comment]
This doesn't hide the fact that a release is needed, but you can use master in your project.

**Comment by ganeshk-ai** [comment]
I am using master in my project but i could use the tag.

**Comment by brandonhilkert** [comment]
@bendiken Can you release the `0.4.0` version to Rubygems?

**Comment by FreekingDean** [comment]
@brandonhilkert It looks like 0.4.0 is on ruby gems https://rubygems.org/gems/rack-throttle

**Comment by brandonhilkert** [comment]
@FreekingDean That's right. We just need a release of the latest code. Sorry for the confusion.

**Comment by FreekingDean** [comment]
Err, 0.4.1 since it was mostly a bug patch to add seconds back in.

**Comment by FreekingDean** [comment]
Hi all, just wanted to let you know there is now a tag for 0.4.1 that points to the current use of seconds in master.

Aka the merge of #25

**Comment by FreekingDean** [comment]
I can release the gem once we merge #31

**Comment by FreekingDean** [comment]
https://rubygems.org/gems/rack-throttle/versions/0.4.1
Out now! :) I'm gonna close this as I just released it!
