### ISSUE TITLE
Missing minute directive in second.rb cache_key

### ISSUE THREAD

**Issue by ganeshk-ai** [dryruby/rack-throttle#29]
In `Second#cache_key` method, minute directive is missing. This caused some incorrect cache hits when run in same second of same hour.

**Current**:  [super, Time.now.strftime('%Y-%m-%dT%H:%S')].join(':')

**Correct**:  [super, Time.now.strftime('%Y-%m-%dT%H:%M:%S')].join(':')

**Comment by FreekingDean** [comment]
Just as a heads up, I am working on this!
