### ISSUE TITLE
Key conflict when combining various throttling constraints into one overall policy

### ISSUE THREAD

**Issue by GuyPaddock** [dryruby/rack-throttle#35]
Under the section of the Readme entitled "Combining various throttling constraints into one overall policy", the following example is provided:

    use Rack::Throttle::Daily,    :max => 1000  # requests
    use Rack::Throttle::Hourly,   :max => 100   # requests
    use Rack::Throttle::Minute,   :max => 60    # requests
    use Rack::Throttle::Second,   :max => 1     # requests
    use Rack::Throttle::Interval, :min => 3.0   # seconds

The only problem with this approach is that the cache keys for the same second, minute, etc can clash.

For example, consider that you have defined the throttling policy exactly as described above. Now consider the following:
- At 12:11:10 PM, assume that `throttle:10.0.2.2:2016-10-05T12:11` (the current minute) is set to 59.
- At 12:11:10 PM, a request comes in from 10.0.2.2, which is allowed, because the max is 60 per minute. The key is now incremented to 60.
- At 12:11:11 PM, a request comes in from 10.0.2.2, which is blocked because the key for the per-second policy is the same as the minute policy -- `throttle:10.0.2.2:2016-10-05T12:11` -- which is currently 30, greatly exceeding the maximum of 1 per second.

~~The same thing happens at 12:12:00 PM, if the per-hour counter is higher than the max for the per-minute counter.~~

This looks like just a copy & paste error with the cache key for `Rack::Throttle::Second`.

Ideally, these keys would be distinct.

**Comment by FreekingDean** [comment]
I believe you might be talking about #29 ? Which was a copy/paste error. It is fixed as of #33

**Comment by GuyPaddock** [comment]
My bad; you are correct. Closing out!
