### ISSUE TITLE
README in latest release & tagging

### ISSUE THREAD

**Issue by jaydorsey** [dryruby/rack-throttle#55]
**Describe the bug**

This is a minor bug I noticed today, and it likely won't affect many people. When running `solargraph bundle` locally, I got an error while building the yard docs for rack-throttle 0.7.0. 

    No such file or directory @ rb_sysopen - README (Errno::ENOENT)

After doing some digging, I noticed the README in the current published version is a symlink to a file that doesn't exist in the gem (README -> README.md). I couldn't confirm this immediately because of two other minor housekeeping issues:

- Rubygems.org probably needs an update (the gem still points to bendiken/rack-throttle, which correctly forwards to this repo) to reduce confusion
- Published gem versions after 0.5.0 don't appear tagged, or as releases on this repo (this was confusing, coupled with the item above I wasn't sure if there was 2 rack-throttles or not)

**To reproduce**

I was running `solargraph bundle` on a repository that had the `rack-throttle` in the Gemfile, but I think this probably affects anyone trying to builds the docs w/ yard

1. Download the build gem from here: https://rubygems.org/downloads/rack-throttle-0.7.0.gem
2. Extract/open view it however you would normally (I just unzipped everything)
3. Observe a README symlink, but no README.md

![image](https://user-images.githubusercontent.com/191564/76100366-c34d4200-5f89-11ea-9d17-a473702a4d26.png)

**Expected behavior**

This appears to be fixed in latest master, but the the latest published version isn't correct

**Additional context**

I don't think there's anything I can contribute, PR wise, since it appears fixed in master but I'm happy to help validate after the new version is published. I can certainly point to master for now but it would be nice to see a new release published & the links updated (and versions tagged in github also)

**Comment by FreekingDean** [comment]
Good callout! I can't get in contact with @artob to setup a CI/CD pipeline to automate this unfortunately. Ill manually push an update out (as well as a tagged release). Im also going to build a deprecation PR as I believe `rack-attack` is more full featured, supported, and the better alternative for those looking to do throttling in rack apps.
