### ISSUE TITLE
No such middleware to insert after: Rack::Lock

### ISSUE THREAD

**Issue by ghost** [dryruby/rack-throttle#7]
Hi

I'm using Rails 4, added custom lib that uses rack-throttle.
So, deploying failing with this notice

"No such middleware to insert after: Rack::Lock"

What is the workaround?
Thanks

**Comment by switzersc** [comment]
Rack::Lock isn't in Rails 4 production env anymore, so use a different library. I use Rack::Runtime --

`config.middleware.insert_after Rack::Runtime, 'RateLimit'`

**Comment by FreekingDean** [comment]
Because this is now 3 years old, and I believe either an implementation issue, or was an issue with the previous README I am going to close it. Please re-open if you need further assistance with this!
